# Disable the newline at the start of the prompt
add_newline         = false
# Overwrite a default_prompt_order and  use custom prompt_order
#prompt_order=["rust","line_break","package","line_break","character"]
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout        = 10

[username]
disabled            = true
show_always         = false

[time]
disabled            = false

[directory]
disabled            = false
truncation_length   = 12
truncate_to_repo    = false

[cmd_duration]
disabled            = true 
min_time            = 5

[kubernetes]
disabled            = false
[kubernetes.context_aliases]
# Contexts from GKE, AWS and other cloud providers usually carry additional
# information, like the region/zone.  The following entry matches on the GKE
# format (`gke_projectname_zone_cluster-name`) and renames every matching kube
# context into a more readable format (`gke-cluster-name`):
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[git_status]
disabled            = true

[gcloud]
format              = '[$symbol$project(\($region\))]($style)'

[nodejs]
disabled            = true
