# Disable the newline at the start of the prompt
add_newline         = false
# Overwrite a default_prompt_order and  use custom prompt_order
#prompt_order=["rust","line_break","package","line_break","character"]
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout        = 10

[username]
disabled            = false
show_always         = true

[time]
disabled            = false

[directory]
disabled            = false
truncation_length   = 12
truncate_to_repo    = false

[cmd_duration]
disabled            = true 
min_time            = 5

[kubernetes]
disabled            = false
